AWSTemplateFormatVersion: 2010-09-09
Description: Creates a simple DynamoDB table
Metadata: 

Parameters: 
  DynamoAtributo:
    Type: String
  DynamoNombre:
    Type: String

Resources: 
  DynamoFromZero: #Resource name
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: !Ref DynamoAtributo # Uses intrisec function
          AttributeType: S
      KeySchema: 
        - AttributeName: !Ref DynamoAtributo
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification: 
        SSEEnabled: true
      TableName: !Ref DynamoNombre


Outputs:
  NombreDynamoRecurso:
    Value: !Ref DynamoFromZero
    Export: DynamoNombre #Importante este campo