AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AppName:
    Type: String

Resources:
  AppBuilder:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: "CODEPIPELINE"
      Description: !Join [' ',["A simple builder for", !Ref AppName]]
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"

        Image: "aws/codebuild/amazonlinux2-x86_64-standard:5.0"


        Type: "LINUX_CONTAINER "
      Name: !Join ['-', [ !Ref AppName, 'build', !Sub '${AWS::Region}']]
      ServiceRole: !ImportValue AppCodeBuildRoleArn # Required
      Source:
        BuildSpec: "config/buildspec.yml"
        Type: "CODEPIPELINE"
      Tags: 
        - Key: 'organization'
          Value: 'joseDev'
        - Key: 'cfn'
          Value: 'pipeline'

Outputs:
  AppBuilderName:
    Value: !Ref AppBuilder
    Export: AppBuilderName