AWSTemplateFormatVersion: 2010-09-09
Parameters:
  AppName:
    Description: Name for the new pipeline
    Type: String
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: 'Name of the pipeline'
        Parameters:
          - AppName
    ParameterLabels:
      AppName:
        default: 'Insert the name for the new Pipeline'
Resources:
  AppArtifactsBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AppName: !Ref AppName
      TemplateURL: https://nested-pipeline.s3.amazonaws.com/templates/artifact-bucket.yml

  AppRoleStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: AppArtifactsBucket
    Properties:
      Parameters:
        AppName: !Ref AppName
      TemplateURL: https://nested-pipeline.s3.amazonaws.com/templates/roles.yml # Required
  
  AppPipeline:
    Type: AWS::CloudFormation::Stack
    DependsOn: AppRoleStack
    Properties:
      Parameters:
        AppName: !Ref AppName
      TemplateURL: #TODO
  
  AppRepository:
    Type: AWS::CloudFormation::Stack
    DependsOn: AppRoleStack
    Properties:
      Parameters:
        AppName: !Ref AppName
      TemplateURL: #TODO

  AppBuildProject:
    Type: AWS::CloudFormation::Stack
    DependsOn: AppRoleStack
    Properties:
      Parameters:
        AppName: !Ref AppName
      TemplateURL: #TODO

