AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AppName:
    Type: String

Resources:
  AppRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryDescription: !Join [' ',["Repository created for he pipeline", !Ref AppName]]
      RepositoryName: !Ref AppName # Required
      Tags: 
        - Key: 'organization'
          Value: 'joseDev'
        - Key: 'cfn'
          Value: 'pipeline'

Outputs:
  AppRepo:
    Value: !GetAtt AppRepository
    Export:
      Name: AppRepo
  AppRepoName:
    Value: !GetAtt AppRepository.Name
    Export:
      Name: AppRepoName   
  AppRepoNameArn:
    Value: !GetAtt AppRepository.Arn
    Export:
      Name: AppRepoNameArn   